# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KakaoApiTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KakaoApiTest
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  target 'KakaoApiTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
