# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KakaoApiTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KakaoApiTest
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher', '~> 4.10.1'
  pod 'PKHUD', '~> 5.0'

  target 'KakaoApiTestTests' do
    pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher', '~> 4.10.1'
    pod 'PKHUD', '~> 5.0'
  end

end
